%This script performs a bulk analysis of the unfolding forces in the April
%data set
%
%Steven Large
%April 28th 2017

UnfoldForceOFw1 = CalculateUnfoldingForce(ForceTraceOFw1,TraceOptimalFw1);
UnfoldForceOFw2 = CalculateUnfoldingForce(ForceTraceOFw2,TraceOptimalFw2);
UnfoldForceOFw3 = CalculateUnfoldingForce(ForceTraceOFw3,TraceOptimalFw3);
UnfoldForceOFw4 = CalculateUnfoldingForce(ForceTraceOFw4,TraceOptimalFw4);
UnfoldForceOFw5 = CalculateUnfoldingForce(ForceTraceOFw5,TraceOptimalFw5);
UnfoldForceOFw6 = CalculateUnfoldingForce(ForceTraceOFw6,TraceOptimalFw6);
UnfoldForceOFw7 = CalculateUnfoldingForce(ForceTraceOFw7,TraceOptimalFw7);
UnfoldForceOFw8 = CalculateUnfoldingForce(ForceTraceOFw8,TraceOptimalFw8);
UnfoldForceOFw9 = CalculateUnfoldingForce(ForceTraceOFw9,TraceOptimalFw9);
UnfoldForceOFw10 = CalculateUnfoldingForce(ForceTraceOFw10,TraceOptimalFw10);
UnfoldForceOFw11 = CalculateUnfoldingForce(ForceTraceOFw11,TraceOptimalFw11);
UnfoldForceOFw12 = CalculateUnfoldingForce(ForceTraceOFw12,TraceOptimalFw12);
UnfoldForceOFw13 = CalculateUnfoldingForce(ForceTraceOFw13,TraceOptimalFw13);
UnfoldForceOFw14 = CalculateUnfoldingForce(ForceTraceOFw14,TraceOptimalFw14);
UnfoldForceOFw15 = CalculateUnfoldingForce(ForceTraceOFw15,TraceOptimalFw15);
UnfoldForceOFw16 = CalculateUnfoldingForce(ForceTraceOFw16,TraceOptimalFw16);
UnfoldForceOFw17 = CalculateUnfoldingForce(ForceTraceOFw17,TraceOptimalFw17);
UnfoldForceOFw18 = CalculateUnfoldingForce(ForceTraceOFw18,TraceOptimalFw18);
UnfoldForceOFw19 = CalculateUnfoldingForce(ForceTraceOFw19,TraceOptimalFw19);
UnfoldForceOFw20 = CalculateUnfoldingForce(ForceTraceOFw20,TraceOptimalFw20);
UnfoldForceOFw21 = CalculateUnfoldingForce(ForceTraceOFw21,TraceOptimalFw21);
UnfoldForceOFw22 = CalculateUnfoldingForce(ForceTraceOFw22,TraceOptimalFw22);
UnfoldForceOFw23 = CalculateUnfoldingForce(ForceTraceOFw23,TraceOptimalFw23);
UnfoldForceOFw24 = CalculateUnfoldingForce(ForceTraceOFw24,TraceOptimalFw24);
UnfoldForceOFw25 = CalculateUnfoldingForce(ForceTraceOFw25,TraceOptimalFw25);

UnfoldForceORev1 = CalculateUnfoldingForce(ForceTraceORev1,TraceOptimalRev1);
UnfoldForceORev2 = CalculateUnfoldingForce(ForceTraceORev2,TraceOptimalRev2);
UnfoldForceORev3 = CalculateUnfoldingForce(ForceTraceORev3,TraceOptimalRev3);
UnfoldForceORev4 = CalculateUnfoldingForce(ForceTraceORev4,TraceOptimalRev4);
UnfoldForceORev5 = CalculateUnfoldingForce(ForceTraceORev5,TraceOptimalRev5);
UnfoldForceORev6 = CalculateUnfoldingForce(ForceTraceORev6,TraceOptimalRev6);
UnfoldForceORev7 = CalculateUnfoldingForce(ForceTraceORev7,TraceOptimalRev7);
UnfoldForceORev8 = CalculateUnfoldingForce(ForceTraceORev8,TraceOptimalRev8);
UnfoldForceORev9 = CalculateUnfoldingForce(ForceTraceORev9,TraceOptimalRev9);
UnfoldForceORev10 = CalculateUnfoldingForce(ForceTraceORev10,TraceOptimalRev10);
UnfoldForceORev11 = CalculateUnfoldingForce(ForceTraceORev11,TraceOptimalRev11);
UnfoldForceORev12 = CalculateUnfoldingForce(ForceTraceORev12,TraceOptimalRev12);
UnfoldForceORev13 = CalculateUnfoldingForce(ForceTraceORev13,TraceOptimalRev13);
UnfoldForceORev14 = CalculateUnfoldingForce(ForceTraceORev14,TraceOptimalRev14);
UnfoldForceORev15 = CalculateUnfoldingForce(ForceTraceORev15,TraceOptimalRev15);
UnfoldForceORev16 = CalculateUnfoldingForce(ForceTraceORev16,TraceOptimalRev16);
UnfoldForceORev17 = CalculateUnfoldingForce(ForceTraceORev17,TraceOptimalRev17);
UnfoldForceORev18 = CalculateUnfoldingForce(ForceTraceORev18,TraceOptimalRev18);
UnfoldForceORev19 = CalculateUnfoldingForce(ForceTraceORev19,TraceOptimalRev19);
UnfoldForceORev20 = CalculateUnfoldingForce(ForceTraceORev20,TraceOptimalRev20);
UnfoldForceORev21 = CalculateUnfoldingForce(ForceTraceORev21,TraceOptimalRev21);
UnfoldForceORev22 = CalculateUnfoldingForce(ForceTraceORev22,TraceOptimalRev22);
UnfoldForceORev23 = CalculateUnfoldingForce(ForceTraceORev23,TraceOptimalRev23);
UnfoldForceORev24 = CalculateUnfoldingForce(ForceTraceORev24,TraceOptimalRev24);
UnfoldForceORev25 = CalculateUnfoldingForce(ForceTraceORev25,TraceOptimalRev25);

UnfoldForceNFw1 = CalculateUnfoldingForce(ForceTraceNFw1,TraceNaiveFw1);
UnfoldForceNFw2 = CalculateUnfoldingForce(ForceTraceNFw2,TraceNaiveFw2);
UnfoldForceNFw3 = CalculateUnfoldingForce(ForceTraceNFw3,TraceNaiveFw3);
UnfoldForceNFw4 = CalculateUnfoldingForce(ForceTraceNFw4,TraceNaiveFw4);
UnfoldForceNFw5 = CalculateUnfoldingForce(ForceTraceNFw5,TraceNaiveFw5);
UnfoldForceNFw6 = CalculateUnfoldingForce(ForceTraceNFw6,TraceNaiveFw6);
UnfoldForceNFw7 = CalculateUnfoldingForce(ForceTraceNFw7,TraceNaiveFw7);
UnfoldForceNFw8 = CalculateUnfoldingForce(ForceTraceNFw8,TraceNaiveFw8);
UnfoldForceNFw9 = CalculateUnfoldingForce(ForceTraceNFw9,TraceNaiveFw9);
UnfoldForceNFw10 = CalculateUnfoldingForce(ForceTraceNFw10,TraceNaiveFw10);
UnfoldForceNFw11 = CalculateUnfoldingForce(ForceTraceNFw11,TraceNaiveFw11);
UnfoldForceNFw12 = CalculateUnfoldingForce(ForceTraceNFw12,TraceNaiveFw12);
UnfoldForceNFw13 = CalculateUnfoldingForce(ForceTraceNFw13,TraceNaiveFw13);
UnfoldForceNFw14 = CalculateUnfoldingForce(ForceTraceNFw14,TraceNaiveFw14);
UnfoldForceNFw15 = CalculateUnfoldingForce(ForceTraceNFw15,TraceNaiveFw15);
UnfoldForceNFw16 = CalculateUnfoldingForce(ForceTraceNFw16,TraceNaiveFw16);
UnfoldForceNFw17 = CalculateUnfoldingForce(ForceTraceNFw17,TraceNaiveFw17);
UnfoldForceNFw18 = CalculateUnfoldingForce(ForceTraceNFw18,TraceNaiveFw18);
UnfoldForceNFw19 = CalculateUnfoldingForce(ForceTraceNFw19,TraceNaiveFw19);
UnfoldForceNFw20 = CalculateUnfoldingForce(ForceTraceNFw20,TraceNaiveFw20);
UnfoldForceNFw21 = CalculateUnfoldingForce(ForceTraceNFw21,TraceNaiveFw21);
UnfoldForceNFw22 = CalculateUnfoldingForce(ForceTraceNFw22,TraceNaiveFw22);
UnfoldForceNFw23 = CalculateUnfoldingForce(ForceTraceNFw23,TraceNaiveFw23);
UnfoldForceNFw24 = CalculateUnfoldingForce(ForceTraceNFw24,TraceNaiveFw24);
UnfoldForceNFw25 = CalculateUnfoldingForce(ForceTraceNFw25,TraceNaiveFw25);

UnfoldForceNRev1 = CalculateUnfoldingForce(ForceTraceNRev1,TraceNaiveRev1);
UnfoldForceNRev2 = CalculateUnfoldingForce(ForceTraceNRev2,TraceNaiveRev2);
UnfoldForceNRev3 = CalculateUnfoldingForce(ForceTraceNRev3,TraceNaiveRev3);
UnfoldForceNRev4 = CalculateUnfoldingForce(ForceTraceNRev4,TraceNaiveRev4);
UnfoldForceNRev5 = CalculateUnfoldingForce(ForceTraceNRev5,TraceNaiveRev5);
UnfoldForceNRev6 = CalculateUnfoldingForce(ForceTraceNRev6,TraceNaiveRev6);
UnfoldForceNRev7 = CalculateUnfoldingForce(ForceTraceNRev7,TraceNaiveRev7);
UnfoldForceNRev8 = CalculateUnfoldingForce(ForceTraceNRev8,TraceNaiveRev8);
UnfoldForceNRev9 = CalculateUnfoldingForce(ForceTraceNRev9,TraceNaiveRev9);
UnfoldForceNRev10 = CalculateUnfoldingForce(ForceTraceNRev10,TraceNaiveRev10);
UnfoldForceNRev11 = CalculateUnfoldingForce(ForceTraceNRev11,TraceNaiveRev11);
UnfoldForceNRev12 = CalculateUnfoldingForce(ForceTraceNRev12,TraceNaiveRev12);
UnfoldForceNRev13 = CalculateUnfoldingForce(ForceTraceNRev13,TraceNaiveRev13);
UnfoldForceNRev14 = CalculateUnfoldingForce(ForceTraceNRev14,TraceNaiveRev14);
UnfoldForceNRev15 = CalculateUnfoldingForce(ForceTraceNRev15,TraceNaiveRev15);
UnfoldForceNRev16 = CalculateUnfoldingForce(ForceTraceNRev16,TraceNaiveRev16);
UnfoldForceNRev17 = CalculateUnfoldingForce(ForceTraceNRev17,TraceNaiveRev17);
UnfoldForceNRev18 = CalculateUnfoldingForce(ForceTraceNRev18,TraceNaiveRev18);
UnfoldForceNRev19 = CalculateUnfoldingForce(ForceTraceNRev19,TraceNaiveRev19);
UnfoldForceNRev20 = CalculateUnfoldingForce(ForceTraceNRev20,TraceNaiveRev20);
UnfoldForceNRev21 = CalculateUnfoldingForce(ForceTraceNRev21,TraceNaiveRev21);
UnfoldForceNRev22 = CalculateUnfoldingForce(ForceTraceNRev22,TraceNaiveRev22);
UnfoldForceNRev23 = CalculateUnfoldingForce(ForceTraceNRev23,TraceNaiveRev23);
UnfoldForceNRev24 = CalculateUnfoldingForce(ForceTraceNRev24,TraceNaiveRev24);
UnfoldForceNRev25 = CalculateUnfoldingForce(ForceTraceNRev25,TraceNaiveRev25);


UnfoldForceOFw = [UnfoldForceOFw1,UnfoldForceOFw2,UnfoldForceOFw3,UnfoldForceOFw4,UnfoldForceOFw5,UnfoldForceOFw6,UnfoldForceOFw7,UnfoldForceOFw8,UnfoldForceOFw9,UnfoldForceOFw10,UnfoldForceOFw11,UnfoldForceOFw12,UnfoldForceOFw13,UnfoldForceOFw14,UnfoldForceOFw15,UnfoldForceOFw16,UnfoldForceOFw17,UnfoldForceOFw18,UnfoldForceOFw19,UnfoldForceOFw20,UnfoldForceOFw21,UnfoldForceOFw22,UnfoldForceOFw23,UnfoldForceOFw24,UnfoldForceOFw25];
UnfoldForceORev = [UnfoldForceORev1,UnfoldForceORev2,UnfoldForceORev3,UnfoldForceORev4,UnfoldForceORev5,UnfoldForceORev6,UnfoldForceORev7,UnfoldForceORev8,UnfoldForceORev9,UnfoldForceORev10,UnfoldForceORev11,UnfoldForceORev12,UnfoldForceORev13,UnfoldForceORev14,UnfoldForceORev15,UnfoldForceORev16,UnfoldForceORev17,UnfoldForceORev18,UnfoldForceORev19,UnfoldForceORev20,UnfoldForceORev21,UnfoldForceORev22,UnfoldForceORev23,UnfoldForceORev24,UnfoldForceORev25];
UnfoldForceNRev = [UnfoldForceNRev1,UnfoldForceNRev2,UnfoldForceNRev3,UnfoldForceNRev4,UnfoldForceNRev5,UnfoldForceNRev6,UnfoldForceNRev7,UnfoldForceNRev8,UnfoldForceNRev9,UnfoldForceNRev10,UnfoldForceNRev11,UnfoldForceNRev12,UnfoldForceNRev13,UnfoldForceNRev14,UnfoldForceNRev15,UnfoldForceNRev16,UnfoldForceNRev17,UnfoldForceNRev18,UnfoldForceNRev19,UnfoldForceNRev20,UnfoldForceNRev21,UnfoldForceNRev22,UnfoldForceNRev23,UnfoldForceNRev24,UnfoldForceNRev25];
UnfoldForceNFw = [UnfoldForceNFw1,UnfoldForceNFw2,UnfoldForceNFw3,UnfoldForceNFw4,UnfoldForceNFw5,UnfoldForceNFw6,UnfoldForceNFw7,UnfoldForceNFw8,UnfoldForceNFw9,UnfoldForceNFw10,UnfoldForceNFw11,UnfoldForceNFw12,UnfoldForceNFw13,UnfoldForceNFw14,UnfoldForceNFw15,UnfoldForceNFw16,UnfoldForceNFw17,UnfoldForceNFw18,UnfoldForceNFw19,UnfoldForceNFw20,UnfoldForceNFw21,UnfoldForceNFw22,UnfoldForceNFw23,UnfoldForceNFw24,UnfoldForceNFw25];

